name: build-php-8-3-without-xdebug

on: workflow_dispatch

jobs:
  php-8-3:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: images/php-without-xdebug/8.3
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            jeanmarcos/magento-php-without-xdebug:8.3-fpm
            jeanmarcos/magento-php-without-xdebug:8.3-fpm-0
